### ISSUE TITLE
Bug: Contact is not added as multiple Contact objects

### ISSUE THREAD

**Issue by frrrrry** [AY2324S1-CS2103T-F08-0/tp#100]
When adding a new Person with mutiple contacts, i.e. `add --name Name --contact contact1, contact2`, there should be multiple Contact objects added into the Set of Contacts, but only one Contact object i.e. `[contac1, contact2]` is added instead of `[contact], [contact2]`

**Comment by xxiaoweii** [comment]
```fixed #98```
